import { cn } from "@/lib/utils";

export function Identicon1({ className }: { className?: string }) {
  return (
    <svg
      className={cn(
        "bg-[#ececec] dark:bg-[#282828] rounded-full p-0.5 border border-border dark:border-input",
        className
      )}
      viewBox="-1.5 -1.5 8 8"
      xmlns="http://www.w3.org/2000/svg"
      fill="hsl(320 100% 50%)"
    >
      <title>Identicon</title>
      <rect
        x="0"
        y="3"
        width="1"
        height="1"
      />
      <rect
        x="0"
        y="4"
        width="1"
        height="1"
      />
      <rect
        x="1"
        y="0"
        width="1"
        height="1"
      />
      <rect
        x="2"
        y="1"
        width="1"
        height="1"
      />
      <rect
        x="2"
        y="3"
        width="1"
        height="1"
      />
      <rect
        x="2"
        y="4"
        width="1"
        height="1"
      />
      <rect
        x="4"
        y="3"
        width="1"
        height="1"
      />
      <rect
        x="4"
        y="4"
        width="1"
        height="1"
      />
      <rect
        x="3"
        y="0"
        width="1"
        height="1"
      />
    </svg>
  );
}

export function Identicon2({ className }: { className?: string }) {
  return (
    <svg
      className={cn(
        "bg-[#ececec] dark:bg-[#282828] rounded-full p-0.5 border border-border dark:border-input",
        className
      )}
      viewBox="-1.5 -1.5 8 8"
      xmlns="http://www.w3.org/2000/svg"
      fill="hsl(80 100% 50%)"
    >
      <title>Identicon</title>
      <rect
        x="0"
        y="0"
        width="1"
        height="1"
      />
      <rect
        x="0"
        y="2"
        width="1"
        height="1"
      />
      <rect
        x="0"
        y="3"
        width="1"
        height="1"
      />
      <rect
        x="1"
        y="1"
        width="1"
        height="1"
      />
      <rect
        x="1"
        y="2"
        width="1"
        height="1"
      />
      <rect
        x="1"
        y="3"
        width="1"
        height="1"
      />
      <rect
        x="1"
        y="4"
        width="1"
        height="1"
      />
      <rect
        x="4"
        y="0"
        width="1"
        height="1"
      />
      <rect
        x="4"
        y="2"
        width="1"
        height="1"
      />
      <rect
        x="4"
        y="3"
        width="1"
        height="1"
      />
      <rect
        x="3"
        y="1"
        width="1"
        height="1"
      />
      <rect
        x="3"
        y="2"
        width="1"
        height="1"
      />
      <rect
        x="3"
        y="3"
        width="1"
        height="1"
      />
      <rect
        x="3"
        y="4"
        width="1"
        height="1"
      />
    </svg>
  );
}
